import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/client";
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

// Load DM Sans font with Latin subset
const dmSans = DM_Sans({
  subsets: ["latin"],
});

// Metadata for the application (used for SEO and page <head> elements)
export const metadata: Metadata = {
  title: "Create Next App", // Default page title
  description: "Generated by create next app", // Default meta description
};

// RootLayout – Main layout wrapping all pages with global font and structure
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Content passed from each route
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        {/* Enables URL state syncing for filters and other query params */}
        <NuqsAdapter>
          {/* Wrap all content in tRPC provider for API access */}
          <TRPCReactProvider>
            {children}
            {/* Global toast notifications */}
            <Toaster />
          </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
